// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using web.Data;

#nullable disable

namespace web.Migrations
{
    [DbContext(typeof(EmuzikaContext))]
    [Migration("20250109153219_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("web.Models.Album", b =>
                {
                    b.Property<int>("ID")
                        .HasColumnType("int");

                    b.Property<DateTime>("DatumIzdaje")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IzvajalecID")
                        .HasColumnType("int");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("IzvajalecID");

                    b.ToTable("Album", (string)null);
                });

            modelBuilder.Entity("web.Models.Izvajalec", b =>
                {
                    b.Property<int>("ID")
                        .HasColumnType("int");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("poslusalci")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Izvajalec", (string)null);
                });

            modelBuilder.Entity("web.Models.IzvajalecPesem", b =>
                {
                    b.Property<int>("IzvajalecID")
                        .HasColumnType("int");

                    b.Property<int>("PesemID")
                        .HasColumnType("int");

                    b.Property<int>("ID")
                        .HasColumnType("int");

                    b.HasKey("IzvajalecID", "PesemID");

                    b.HasIndex("PesemID");

                    b.ToTable("IzvajalecPesem", (string)null);
                });

            modelBuilder.Entity("web.Models.Pesem", b =>
                {
                    b.Property<int>("ID")
                        .HasColumnType("int");

                    b.Property<int>("AlbumID")
                        .HasColumnType("int");

                    b.Property<int>("Dolzina")
                        .HasColumnType("int");

                    b.Property<string>("Naslov")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Ocena")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("AlbumID");

                    b.ToTable("Pesem", (string)null);
                });

            modelBuilder.Entity("web.Models.Album", b =>
                {
                    b.HasOne("web.Models.Izvajalec", "Izvajalec")
                        .WithMany("Albumi")
                        .HasForeignKey("IzvajalecID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Izvajalec");
                });

            modelBuilder.Entity("web.Models.IzvajalecPesem", b =>
                {
                    b.HasOne("web.Models.Izvajalec", "izvajalec")
                        .WithMany("izvajalecPesems")
                        .HasForeignKey("IzvajalecID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("web.Models.Pesem", "pesem")
                        .WithMany("izvajalecPesems")
                        .HasForeignKey("PesemID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("izvajalec");

                    b.Navigation("pesem");
                });

            modelBuilder.Entity("web.Models.Pesem", b =>
                {
                    b.HasOne("web.Models.Album", "Album")
                        .WithMany("Pesmi")
                        .HasForeignKey("AlbumID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Album");
                });

            modelBuilder.Entity("web.Models.Album", b =>
                {
                    b.Navigation("Pesmi");
                });

            modelBuilder.Entity("web.Models.Izvajalec", b =>
                {
                    b.Navigation("Albumi");

                    b.Navigation("izvajalecPesems");
                });

            modelBuilder.Entity("web.Models.Pesem", b =>
                {
                    b.Navigation("izvajalecPesems");
                });
#pragma warning restore 612, 618
        }
    }
}
